/**
 * One-off script: translate demo SysML examples (under prisma/examples/)
 * to Turkish identifiers and write them to prisma/examples-tr/.
 *
 * - Standard Libraries/ is excluded (OMG official library — never translate).
 * - Folder names, file names (without .sysml extension), and identifiers
 *   inside files are translated using IDENT_MAP + FOLDER_MAP + FILE_MAP.
 * - SysML keywords, primitive types, and OMG library namespaces are preserved.
 *
 * Run:  npx tsx scripts/translate-examples.mts
 */

import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { resolve, dirname, join, basename, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(__dirname, '../prisma/examples');
const DST = resolve(__dirname, '../prisma/examples-tr');

// Folders to skip (standard libraries / official OMG content).
const EXCLUDE_DIRS = new Set(['Standard Libraries']);

// ─── Folder name translations ────────────────────────────────────────────────
const FOLDER_MAP: Record<string, string> = {
  'Behavior': 'Davranis',
  'Cases': 'Senaryolar',
  'Definitions and Usages': 'Tanimlar ve Kullanimlar',
  'Requirements': 'Gereksinimler',
  'States': 'Durumlar',
  'Structure': 'Yapi',
  'Vehicle Model': 'Arac Modeli',
  'Views and Metadata': 'Gorunumler ve UstVeri',
};

// ─── File name translations (without .sysml extension) ──────────────────────
const FILE_MAP: Record<string, string> = {
  // Behavior
  'Action_Control_Flow': 'Eylem_Kontrol_Akisi',
  'Action_Definitions': 'Eylem_Tanimlari',
  'Action_Flow': 'Eylem_Akisi',
  'Action_Parameters': 'Eylem_Parametreleri',
  'Decision_and_Merge': 'Karar_ve_Birlesim',
  'If_Then_Else': 'Eger_O_Halde',
  'Loops_and_Conditionals': 'Donguler_ve_Kosullar',
  'Messages_and_Sequences': 'Mesajlar_ve_Sekanslar',
  'Occurrences_and_Temporal': 'Olaylar_ve_Zamansal',
  'Perform_and_Exhibit': 'Yurut_ve_Sergile',
  'Send_Accept_Actions': 'Gonder_Kabul_Eylemleri',
  'Succession_Flow': 'Ardisik_Akis',
  // Cases
  'Analysis_and_Verification': 'Analiz_ve_Dogrulama',
  'Case_Definitions': 'Senaryo_Tanimlari',
  'Use_Cases': 'Kullanim_Senaryolari',
  // Definitions and Usages
  'Calculations_and_Constraints': 'Hesaplamalar_ve_Kisitlar',
  'Enumerations': 'Numaralandirmalar',
  'Items_and_Ports': 'Ogeler_ve_Portlar',
  'Part_and_Attribute_Definitions': 'Parca_ve_Oznitelik_Tanimlari',
  'Redefinition_and_Subsetting': 'Yeniden_Tanimlama_ve_Alt_Kume',
  'Specialization_and_Redefinition': 'Ozellestirme_ve_Yeniden_Tanimlama',
  // Requirements
  'Requirement_Definitions': 'Gereksinim_Tanimlari',
  'Requirements_Advanced': 'Gereksinimler_Gelismis',
  'Satisfy_and_Verify': 'Karsila_ve_Dogrula',
  'Vehicle_Requirements': 'Arac_Gereksinimleri',
  // States
  'Parallel_States': 'Paralel_Durumlar',
  'State_Definitions': 'Durum_Tanimlari',
  'Vehicle_States': 'Arac_Durumlari',
  // Structure
  'Allocations_and_Flows': 'Atamalar_ve_Akislar',
  'Binding_and_Succession': 'Baglama_ve_Ardisiklik',
  'Connections_and_Interfaces': 'Baglantilar_ve_Arayuzler',
  'Connections_Flows_Occurrences': 'Baglantilar_Akislar_Olaylar',
  'Interconnection': 'AraBaglanti',
  'Interfaces_and_Bindings': 'Arayuzler_ve_Baglamalar',
  'Parts_Tree': 'Parcalar_Agaci',
  'Ports_and_Flows': 'Portlar_ve_Akislar',
  // Vehicle Model
  'SimpleVehicleModel': 'BasitAracModeli',
  // Views and Metadata
  'Metadata_Example': 'UstVeri_Ornegi',
  'Views_Advanced': 'Gorunumler_Gelismis',
  'Views_and_Viewpoints': 'Gorunumler_ve_BakisAcilari',
};

// ─── Identifier translation map ─────────────────────────────────────────────
// ASCII-only (no Turkish chars) so parser word boundaries (`\b`) work safely.
// Keys must NOT be SysML keywords or primitive types.
const IDENT_MAP: Record<string, string> = {
  // Packages (UpperCamelCase)
  ActionControlFlow: 'EylemKontrolAkisi',
  ActionDefinitions: 'EylemTanimlari',
  ActionFlow: 'EylemAkisi',
  ActionParameters: 'EylemParametreleri',
  ActionTree: 'EylemAgaci',
  AllocationsAndFlows: 'AtamalarVeAkislar',
  AnalysisAndVerification: 'AnalizVeDogrulama',
  BindingAndSuccession: 'BaglamaVeArdisiklik',
  CalculationsAndConstraints: 'HesaplamalarVeKisitlar',
  CaseDefinitions: 'SenaryoTanimlari',
  Connections: 'Baglantilar',
  ConnectionsFlowsOccurrences: 'BaglantilarAkislarOlaylar',
  Definitions: 'Tanimlar',
  Enumerations: 'Numaralandirmalar',
  IfThenElse: 'EgerOHalde',
  InterfacesAndBindings: 'ArayuzlerVeBaglamalar',
  ItemsAndPorts: 'OgelerVePortlar',
  LoopsAndConditionals: 'DonglerVeKosullar',
  MessagesAndSequences: 'MesajlarVeSekanslar',
  Messages: 'Mesajlar',
  MetadataExample: 'UstVeriOrnegi',
  OccurrencesAndTemporal: 'OlaylarVeZamansal',
  ParallelStates: 'ParalelDurumlar',
  PartDefinitions: 'ParcaTanimlari',
  PartsTree: 'ParcalarAgaci',
  PartsTreeView: 'ParcalarAgaciGorunumu',
  PerformAndExhibit: 'YurutVeSergile',
  PortsAndFlows: 'PortlarVeAkislar',
  RedefinitionAndSubsetting: 'YenidenTanimlamaVeAltKume',
  RequirementDefinitions: 'GereksinimTanimlari',
  Requirements: 'Gereksinimler',
  RequirementsAdvanced: 'GereksinimlerGelismis',
  SatisfyAndVerify: 'KarsilaVeDogrula',
  SendAcceptActions: 'GonderKabulEylemleri',
  SimpleVehicleModel: 'BasitAracModeli',
  Snapshots: 'AnliklarPaketi',
  Specialization: 'Ozellestirme',
  Stakeholders: 'Paydaslar',
  StateDefinitions: 'DurumTanimlari',
  States: 'Durumlar',
  StructureViewpoint: 'YapiBakisAcisi',
  SuccessionFlowExample: 'ArdisikAkisOrnegi',
  Temporal: 'Zamansal',
  Testing: 'TestPaketi',
  UseCases: 'KullanimSenaryolari',
  VehicleConfiguration: 'AracYapilandirmasi',
  VehicleDomain: 'AracAlani',
  VehicleRequirements: 'AracGereksinimleri',
  VehicleSafety: 'AracGuvenligi',
  Views: 'Gorunumler',
  ViewsAdvanced: 'GorunumlerGelismis',
  ViewsAndViewpoints: 'GorunumlerVeBakisAcilari',

  // Part definitions (UpperCamelCase)
  Actuator: 'Eyleyici',
  AirbagSystem: 'HavaYastigiSistemi',
  AlloyWheel: 'AlasimliJant',
  AutomaticTransmission: 'OtomatikSanziman',
  Axle: 'Aks',
  Base: 'Taban',
  Battery: 'Batarya',
  BigEngine: 'BuyukMotor',
  BigVehicle: 'BuyukArac',
  BrakeDisc: 'FrenDiski',
  BrakeSystem: 'FrenSistemi',
  BrakingSystem: 'FrenlemeSistemi',
  Camera: 'Kamera',
  Chassis: 'Sasi',
  CombustionEngine: 'IctenYanmaliMotor',
  Controller: 'Denetleyici',
  CoolingSystem: 'SogutmaSistemi',
  Cylinder: 'Silindir',
  Dashboard: 'GostergePaneli',
  Differential: 'Diferansiyel',
  Driver: 'Surucu',
  Driveshaft: 'SaftMili',
  ElectricCar: 'ElektrikliOtomobil',
  ElectricDrivetrain: 'ElektrikliCekisHatti',
  ElectricEngine: 'ElektrikliMotor',
  Engine: 'Motor',
  FrontAxle: 'OnAks',
  FuelTank: 'YakitDeposu',
  Highway: 'Otoyol',
  Motor: 'Motor',
  MonitorSystem: 'IzlemeSistemi',
  Passenger: 'Yolcu',
  Person: 'Kisi',
  Piston: 'Piston',
  PoweredVehicle: 'MotorluArac',
  PowerSupply: 'GucKaynagi',
  RearAxle: 'ArkaAks',
  Safety: 'Guvenlik',
  Sensor: 'Algilayici',
  SmallEngine: 'KucukMotor',
  SmallVehicle: 'KucukArac',
  SportsCar: 'SporOtomobil',
  StarterMotor: 'MarsMotoru',
  SystemModel: 'SistemModeli',
  Tank: 'Depo',
  Transmission: 'Sanziman',
  TurboEngine: 'TurboMotor',
  Vehicle: 'Arac',
  Wheel: 'Tekerlek',

  // Port definitions
  ConjFuelPort: 'TersYakitPortu',
  ControlPort: 'KontrolPortu',
  DataPort: 'VeriPortu',
  DrivePwrPort: 'CekisGucPortu',
  ElectricPort: 'ElektrikPortu',
  EnginePort: 'MotorPortu',
  FuelCmdPort: 'YakitKomutPortu',
  FuelInPort: 'YakitGirisPortu',
  FuelOutPort: 'YakitCikisPortu',
  FuelPort: 'YakitPortu',
  FuelingPort: 'YakitDoldurmaPortu',
  IgnitionCmdPort: 'AtesleKomutPortu',
  PowerInPort: 'GucGirisPortu',
  PowerOutPort: 'GucCikisPortu',
  PowerPort: 'GucPortu',

  // Item definitions
  Acknowledgment: 'Onay',
  BrakeCommand: 'FrenKomutu',
  Coolant: 'Sogutucu',
  ControlSignal: 'KontrolSinyali',
  CrashEvent: 'CarpismaOlayi',
  DashboardUpdate: 'GostergeGuncellemesi',
  DataBus: 'VeriYolu',
  DataSignal: 'VeriSinyali',
  ElectricalPower: 'ElektrikGucu',
  Electricity: 'Elektrik',
  EngineStatus: 'MotorDurumu',
  Exhaust: 'Egzoz',
  ExhaustGas: 'EgzozGazi',
  Fuel: 'Yakit',
  FuelCmd: 'YakitKomutu',
  Image: 'Goruntu',
  IgnitionCmd: 'AtesleKomutu',
  IgnitionSignal: 'AtesleSinyali',
  LogResult: 'SonucKaydi',
  MaintenanceEvent: 'BakimOlayi',
  Picture: 'Resim',
  Power: 'Guc',
  Pressure: 'Basinc',
  RPM: 'DevSayisi',
  RPMReading: 'DevSayisiOkumasi',
  SensorData: 'AlgilayiciVerisi',
  StartRequest: 'BaslatmaIstegi',
  Status: 'Durum',
  StatusReport: 'DurumRaporu',
  Temperature: 'Sicaklik',
  Torque: 'Tork',
  VehicleStart: 'AracBaslangici',

  // Enum definitions and values
  Color: 'Renk',
  ConditionLevel: 'KosulSeviyesi',
  FuelKind: 'YakitTuru',
  FuelType: 'YakitTipi',
  RiskLevel: 'RiskSeviyesi',
  TransmissionMode: 'SanzimanModu',
  // enum value identifiers (lowercase)
  gas: 'benzin',
  diesel: 'dizel',
  Gasoline: 'Benzin',
  Diesel: 'Dizel',
  Manual: 'ManuelMod',
  Automatic: 'OtomatikMod',
  Red: 'Kirmizi',
  Blue: 'Mavi',
  Black: 'Siyah',
  White: 'Beyaz',
  Silver: 'Gumus',

  // Connection / Interface / Flow definitions
  FuelLine: 'YakitHatti',
  FuelInterface: 'YakitArayuzu',
  FuelFlow: 'YakitAkisi',
  FuelTransfer: 'YakitAktarimi',
  PowerInterface: 'GucArayuzu',

  // Action definitions
  Abort: 'GoreviIptal',
  Accelerate: 'Hizlan',
  Amplify: 'Yukselt',
  AmplifyTorque: 'TorkYukselt',
  ApplyParkingBrake: 'ElFreniniUygula',
  Brake: 'Frenle',
  CheckCondition: 'KosulKontrolu',
  CheckReady: 'HazirligiKontrol',
  Compute: 'Hesapla',
  Cooldown: 'Sogume',
  Cruise: 'SeyirHali',
  DataProcessing: 'VeriIsleme',
  DistributeTorque: 'TorkDagit',
  Drive: 'Sur',
  DriveCycle: 'SurusDongusu',
  DriveToDestination: 'HedefeKadarSur',
  EmergencyStop: 'AcilDurus',
  Estimate: 'TahminEt',
  Execute: 'Yurut',
  Exercise: 'Senaryo',
  Exercising: 'Senaryolama',
  Finalize: 'Sonlandir',
  Firing: 'Atesleme',
  Focus: 'Odakla',
  GenerateTorque: 'TorkUret',
  Generate: 'Uret',
  GetInVehicle: 'AracaBin',
  GetOutOfVehicle: 'AractanIn',
  HandleFailure: 'HataIsle',
  HandleSuccess: 'BasariyiIsle',
  Hazirla: 'Hazirla',
  Ignite: 'Atesle',
  IgnitionOnOff: 'AtesleAcKapat',
  Launch: 'Firlat',
  MaintenanceCheck: 'BakimKontrolu',
  MissionControl: 'GorevKontrol',
  MyAction: 'BenimEylemim',
  OnOff: 'AcKapat',
  PerformSelfTest: 'KendiniTestEt',
  Prepare: 'Hazirla',
  ProcessEmergency: 'AcilDurumIsle',
  ProcessError: 'HataDurumunuIsle',
  ProcessNormal: 'NormalIsle',
  ProvidePower: 'GucSagla',
  Release: 'Birak',
  SenseTemperature: 'SicakligiAlgila',
  Shoot: 'Cek',
  Show: 'Goster',
  Start: 'Baslat',
  StartEngine: 'MotoruCalistir',
  StartProcess: 'IslemBaslat',
  StartupSequence: 'BaslatmaDizisi',
  StartVehicle: 'AraciCalistir',
  Steer: 'Direksiyon',
  Step: 'Adim',
  Step1: 'Adim1',
  Step2: 'Adim2',
  Step3: 'Adim3',
  TakePicture: 'ResimCek',
  TaskA: 'GorevA',
  TaskB: 'GorevB',
  TransferTorque: 'TorkAktar',
  TransportPassenger: 'YolcuTasi',
  VehicleStartupSequence: 'AracBaslatmaDizisi',
  WarmUp: 'Isinma',
  Weigh: 'Tart',

  // State definitions
  DrivingStates: 'SurusDurumlari',
  OperatingStates: 'CalismaDurumlari',
  TrafficLightStates: 'TrafikIsigiDurumlari',
  VehicleHealthStates: 'AracSaglikDurumlari',
  VehicleOperatingStates: 'AracCalismaDurumlari',
  VehicleStates: 'AracDurumlari',

  // Requirements / Constraints / Calcs / Concerns
  BrakingDistance: 'FrenlemeMesafesi',
  BrakingRequirement: 'FrenlemeGereksinimi',
  EmergencyMassLimit: 'AcilKutleSiniri',
  FuelConsumption: 'YakitTuketimi',
  FuelEconomyAnalysis: 'YakitEkonomisiAnalizi',
  FuelEconomyCalc: 'YakitEkonomisiHesabi',
  FuelEconomyRequirement: 'YakitEkonomisiGereksinimi',
  MassConstraint: 'KutleKisitlamasi',
  MassLimit: 'KutleSiniri',
  MassReq: 'KutleGereksinim',
  MassRequirement: 'KutleGereksinimi',
  MassTest: 'KutleTesti',
  MaxMassConstraint: 'MaksimumKutleKisitlamasi',
  PerformanceRequirement: 'PerformansGereksinimi',
  ReliabilityConcern: 'GuvenirlikIlgisi',
  SafetyConcern: 'GuvenlikIlgisi',
  SafetyRequirement: 'GuvenlikGereksinimi',
  SafetyView: 'GuvenlikGorunumu',
  SafetyViewpoint: 'GuvenlikBakisAcisi',
  SafetyEngineer: 'GuvenlikMuhendisi',
  SpeedRequirement: 'HizGereksinimi',
  SystemTestCase: 'SistemTestSenaryosu',
  TotalMass: 'ToplamKutle',
  TotalMassCalc: 'ToplamKutleHesabi',

  // Views
  DiagramView: 'DiyagramGorunumu',
  EngineerView: 'MuhendisGorunumu',
  Performance: 'Performans',
  StandardRendering: 'StandartGorselle',
  SystemOverview: 'SistemGenelGorunum',
  TableRendering: 'TabloGorselle',
  TreeRendering: 'AgacGorselle',
  TreeView: 'AgacGorunumu',

  // Occurrences / Individuals
  Vehicle_1: 'Arac_1',

  // ── Attribute names (lowerCamelCase) ────────────────────────────────────
  absVarMi: 'absVarMi',
  acceleratorPosition: 'gazPedaliKonumu',
  actualFuelEconomy: 'mevcutYakitEkonomisi',
  actualLoad: 'mevcutYuk',
  actualMass: 'mevcutKutle',
  approvalStatus: 'onayDurumu',
  approved: 'onaylandi',
  approver: 'onaylayan',
  batteryCapacity: 'bataryaKapasitesi',
  bodyMass: 'govdeKutlesi',
  brakingForce: 'frenlemeKuvveti',
  capacity: 'kapasite',
  cargoMass: 'yukKutlesi',
  cityFuelEconomy: 'sehirYakitEkonomisi',
  collisionDetected: 'carpismaAlgilandi',
  color: 'renk',
  currentTemp: 'mevcutSicaklik',
  cylinders: 'silindirler',
  deployTime: 'aciklimaSuresi',
  diameter: 'cap',
  differentialRatio: 'diferansiyelOrani',
  direction: 'yon',
  displacement: 'silindirHacmi',
  distance: 'mesafe',
  distanceLimit: 'mesafeSiniri',
  driveshaftTorque: 'saftTorku',
  dryMass: 'kuruKutle',
  engineRunning: 'motorCalisiyor',
  engineTorque: 'motorTorku',
  factor: 'faktor',
  fuelEconomy: 'yakitEkonomisi',
  fuelMass: 'yakitKutlesi',
  fuelType: 'yakitTipi',
  fuelUsed: 'kullanilanYakit',
  gearCount: 'vitesSayisi',
  gearSetting: 'vitesAyari',
  highwayFuelEconomy: 'otoyolYakitEkonomisi',
  horsepower: 'beygirGucu',
  inputTorque: 'girdiTorku',
  isABS: 'absVarMi',
  isEmergency: 'acilMi',
  isNormal: 'normalMi',
  isValid: 'gecerliMi',
  level: 'seviye',
  limit: 'sinir',
  loadCapacity: 'yukKapasitesi',
  location: 'konum',
  maintenanceCheck: 'bakimKontrol',
  mass: 'kutle',
  massActual: 'mevcutKutle',
  massLimit: 'kutleSiniri',
  massOk: 'kutleUygun',
  massRequired: 'istenenKutle',
  material: 'malzeme',
  maxCurrent: 'maksimumAkim',
  maxMass: 'maksimumKutle',
  maxSpeed: 'maksimumHiz',
  maximum: 'maksimum',
  measuredValue: 'olculenDeger',
  mileage: 'kilometre',
  minTopSpeed: 'minimumEnHiz',
  minimum: 'minimum',
  octaneRating: 'oktanDerecesi',
  position: 'konum',
  pressure: 'basinc',
  reading: 'okuma',
  reliability: 'guvenirlik',
  required: 'istenen',
  requiredFuelEconomy: 'istenenYakitEkonomisi',
  responseTime: 'tepkiSuresi',
  result: 'sonuc',
  rpm: 'devSayisi',
  signal: 'sinyal',
  speed: 'hiz',
  steeringAngle: 'direksiyonAcisi',
  stoppingDistance: 'durmaMesafesi',
  targetValue: 'hedefDeger',
  threshold: 'esik',
  throttleLevel: 'gazSeviyesi',
  topSpeed: 'enHiz',
  totalMass: 'toplamKutle',
  vehicleMassLimit: 'aracKutleSiniri',
  vehicleMassReq: 'aracKutleGer',
  vehicleMassRequirement: 'aracKutleGereksinimi',
  vehicleSpec: 'aracSart',
  vehicleSpecification: 'aracSartnamesi',
  velocity: 'hiz',

  // ── Usage names (lowerCamelCase) ────────────────────────────────────────
  ac: 'ac',
  accelerate: 'hizlan',
  actuator: 'eyleyici',
  actuatorPort: 'eyleyiciPortu',
  airbag: 'havaYastigi',
  airbags: 'havaYastiklari',
  amplifier: 'yukseltici',
  amplify: 'yukselt',
  amplifyTorque: 'torkYukselt',
  autoTrans: 'otomatikSanziman',
  back: 'arka',
  battery: 'batarya',
  bigEng: 'buyukMotor',
  boardVehicle: 'aracaBin',
  brake: 'fren',
  brakes: 'frenler',
  braking: 'frenleme',
  brakingSpec: 'frenlemeSart',
  brakingSystem: 'frenlemeSistemi',
  calibrateSensor: 'algilayicikalibrasyonu',
  cargo: 'yuk',
  check: 'kontrol',
  checkTemp: 'sicaklikKontrol',
  clutchPort: 'debriyajPortu',
  collision: 'carpisma',
  command: 'komut',
  commandPort: 'komutPortu',
  commPort: 'iletisimPortu',
  components: 'bilesenler',
  conditions: 'kosullar',
  controller: 'denetleyici',
  controlPort: 'kontrolPortu',
  controlSystem: 'kontrolSistemi',
  coolant: 'sogutucu',
  coolantFlow: 'sogutucuAkisi',
  coolantOut: 'sogutucuCikis',
  coolantPort: 'sogutucuPortu',
  cooling: 'sogutma',
  cooldown: 'sogume',
  cyl: 'sil',
  dashboard: 'gostergePaneli',
  data: 'veri',
  dataIn: 'veriGirisi',
  dataLink: 'veriBaglantisi',
  dataOut: 'veriCikis',
  dataPort: 'veriPortu',
  decideNode: 'kararDugumu',
  decision1: 'karar1',
  degraded: 'bozulmus',
  destination: 'hedef',
  differential: 'diferansiyel',
  disc: 'disk',
  displayPort: 'ekranPortu',
  distributeTorque: 'torkDagit',
  doorClosed: 'kapiKapali',
  drive: 'sur',
  drivePwrPort: 'cekisGucPortu',
  driver: 'surucu',
  driverGetIn: 'suruculBinis',
  driverGetOut: 'suruculInis',
  driverReady: 'suruculHazir',
  driveshaft: 'saftMili',
  driveToDestination: 'hedefeSur',
  drivingStates: 'surusDurumlari',
  drivingWheel: 'cekisTekerlegi',
  economy: 'ekonomi',
  electric: 'elektrik',
  end: 'son',
  endA: 'ucA',
  endB: 'ucB',
  eng: 'motor',
  engine: 'motor',
  engineFuel: 'motorYakit',
  enginePort: 'motorPortu',
  engineering: 'muhendislik',
  evaluatePassFail: 'gectiKaldiyiDegerlendir',
  evaluateReading: 'okumayiDegerlendir',
  evaluateResult: 'sonucuDegerlendir',
  exercise: 'calistir',
  exhaustOut: 'egzozCikis',
  exhaustPort: 'egzozPortu',
  exitVehicle: 'aractanIn',
  filtered: 'filtreli',
  finalize: 'sonlandir',
  focus: 'odakla',
  fork1: 'catal1',
  fork2: 'catal2',
  forkNode: 'catalDugum',
  frontAxle: 'onAks',
  frontAxleAssembly: 'onAksGrubu',
  frontWheel: 'onTekerlek',
  frontWheels: 'onTekerlekler',
  fuel: 'yakit',
  fuelCmd: 'yakitKomut',
  fuelFlow: 'yakitAkis',
  fuelIn: 'yakitGiris',
  fuelInPort: 'yakitGirisPortu',
  fuelInterface: 'yakitArayuzu',
  fuelKind: 'yakitTuru',
  fuelLine: 'yakitHatti',
  fuelOut: 'yakitCikis',
  fuelOutPort: 'yakitCikisPortu',
  fuelPort: 'yakitPortu',
  fuelReturn: 'yakitDonus',
  fuelTank: 'yakitDeposu',
  generate: 'uret',
  generateTorque: 'torkUret',
  generator: 'uretici',
  handleEvent: 'olayIsle',
  handleFailure: 'hataIsle',
  handler: 'islemci',
  handleSuccess: 'basariyiIsle',
  hataDurumunuIsle: 'hataDurumunuIsle',
  healthStates: 'saglikDurumlari',
  hierarchy: 'hiyerarsi',
  high: 'yuksek',
  idle: 'bosta',
  ig: 'at',
  ignition: 'atesle',
  ignitionCmd: 'atesleKomut',
  ignitionKey: 'kontakAnahtari',
  ignitionOff: 'atesleKapat',
  ignitionOn: 'atesleAc',
  ignitionOnOff: 'atesleAcKapat',
  image: 'goruntu',
  input: 'girdi',
  iterate: 'tekrarla',
  join1: 'birlestir1',
  join2: 'birlestir2',
  joinNode: 'birlestirDugum',
  keyInserted: 'anahtarTakildi',
  leftFront: 'solOn',
  log: 'gunluk',
  low: 'dusuk',
  maintenance: 'bakim',
  massCheck: 'kutleKontrolu',
  massReq: 'kutleGer',
  massTest: 'kutleTesti',
  measure: 'olc',
  medium: 'orta',
  merge1: 'birlesim1',
  mergeNode: 'birlesimDugumu',
  monitorLoop: 'izlemeDongusu',
  motion: 'hareket',
  motor: 'motor',
  moving: 'hareketHalinde',
  myVehicle: 'benimAracim',
  normal: 'normal',
  off: 'kapali',
  on: 'acik',
  operatingStates: 'calismaDurumlari',
  output: 'cikti',
  outputTorque: 'ciktiTorku',
  parallel: 'paralel',
  parts: 'parcalar',
  passenger: 'yolcu',
  passengerGetIn: 'yolcuBinis',
  passengerGetOut: 'yolcuInis',
  passengers: 'yolcular',
  perfReq: 'performansGer',
  performance: 'performans',
  picture: 'resim',
  piston: 'piston',
  point: 'nokta',
  power: 'guc',
  powerIn: 'gucGiris',
  powerLink: 'gucBaglantisi',
  powerOut: 'gucCikis',
  powerPort: 'gucPortu',
  powerSupply: 'gucKaynagi',
  prepare: 'hazirla',
  process: 'islem',
  processAlert: 'uyariIsle',
  processData: 'veriIsle',
  processEmergency: 'acilDurumIsle',
  processNormal: 'normalIsle',
  processError: 'hataDurumunuIsle',
  processor: 'islemci',
  providePower: 'gucSagla',
  raceEng: 'yarisMotor',
  raceWheel: 'yarisTekerlek',
  rearAxle: 'arkaAks',
  rearAxleAssembly: 'arkaAksGrubu',
  rearWheel: 'arkaTekerlek',
  rearWheel1: 'arkaTekerlek1',
  rearWheel2: 'arkaTekerlek2',
  rearWheels: 'arkaTekerlekler',
  readSensor: 'algilayiciOku',
  receiveIgnition: 'atesleAl',
  receiveRPM: 'devSayisiAl',
  receiveStart: 'baslatmaAl',
  receiveStatus: 'durumAl',
  regulatoryBody: 'duzenleyiciOrgan',
  reliabilityCheck: 'guvenirlikKontrol',
  reportStatus: 'durumBildir',
  running: 'calisiyor',
  safety: 'guvenlik',
  safetyConcern: 'guvenlikIlgisi',
  safetyEngineer: 'guvenlikMuhendisi',
  safetySystem: 'guvenlikSistemi',
  safetyTest: 'guvenlikTesti',
  safetyVP: 'guvenlikBA',
  selfTest: 'kendiniTest',
  sendIgnition: 'atesleGonder',
  sendRPM: 'devSayisiGonder',
  sendStart: 'baslatmaGonder',
  sensor: 'algilayici',
  sensorArray: 'algilayiciDizisi',
  sensorPort: 'algilayiciPortu',
  shaftPort: 'milPortu',
  shoot: 'cek',
  shutdown: 'kapanis',
  smallEng: 'kucukMotor',
  source: 'kaynak',
  span: 'sure',
  speedCheck: 'hizKontrolu',
  sportWheel: 'sporTekerlek',
  starterMotor: 'marsMotoru',
  starting: 'baslatiliyor',
  startEngine: 'motorCalistir',
  startup: 'baslangic',
  states: 'durumlar',
  step1: 'adim1',
  step2: 'adim2',
  step3: 'adim3',
  stop: 'durdur',
  stopped: 'durdu',
  store: 'sakla',
  storeResult: 'sonucuSakla',
  systemBoot: 'sistemBaslatma',
  systemUnderTest: 'testEdilenSistem',
  tank: 'depo',
  testObjective: 'testHedefi',
  trans: 'sanziman',
  transferTorque: 'torkAktar',
  transmission: 'sanziman',
  transmissionTorque: 'sanzimanTorku',
  transportPassenger: 'yolcuTasi',
  transportTrip: 'tasimaYolculugu',
  treeRender: 'agacGorselle',
  trip: 'seyahat',
  turboPiston: 'turboPiston',
  turnOn: 'ac',
  vehicle: 'arac',
  vehicleStates: 'aracDurumlari',
  waitForStart: 'baslamayiBekle',
  warmup: 'isinma',
  weighVehicle: 'araciTart',
  wheelTorque: 'tekerlekTorku',
  workflow: 'isAkisi',
  // State machine transition identifiers
  off_starting: 'kapali_baslatiliyor',
  starting_on: 'baslatiliyor_acik',
  on_off: 'acik_kapali',
  off_on: 'kapali_acik',
  normal_degraded: 'normal_bozulmus',
  degraded_normal: 'bozulmus_normal',
  normal_maintenance: 'normal_bakim',
  maintenance_normal: 'bakim_normal',
  start_moving: 'baslat_hareket',
};

// ─── SysML keywords / primitives / namespaces NEVER to translate ────────────
// These keys must be excluded from the map even if accidentally added.
const NEVER_TRANSLATE = new Set([
  // SysML keywords
  'part', 'def', 'attribute', 'port', 'item', 'enum', 'action', 'state',
  'requirement', 'constraint', 'calc', 'package', 'import', 'use', 'case',
  'view', 'viewpoint', 'allocation', 'occurrence', 'individual', 'snapshot',
  'timeslice', 'metadata', 'concern', 'verification', 'analysis', 'rendering',
  'alias', 'comment', 'doc', 'message', 'flow', 'in', 'out', 'inout', 'first',
  'then', 'transition', 'satisfy', 'verify', 'allocate', 'fork', 'join',
  'decide', 'merge', 'if', 'perform', 'exhibit', 'entry', 'do', 'exit', 'send',
  'accept', 'event', 'bind', 'by', 'of', 'from', 'to', 'return', 'interface',
  'connection', 'connect', 'after', 'before', 'at', 'until', 'while', 'for',
  'expose', 'subject', 'actor', 'stakeholder', 'objective', 'render', 'specifies',
  'frame', 'private', 'public', 'protected', 'abstract', 'redefines', 'specializes',
  'subsets', 'feature', 'ref', 'as', 'all', 'is', 'not', 'and', 'or', 'over',
  'specified', 'block', 'assert', 'assign', 'compute', 'iterate', 'loop', 'guard',
  'until', 'about', 'concerned', 'reverses', 'meets',
  // Primitive types
  'Real', 'Integer', 'Boolean', 'String', 'true', 'false', 'null',
  // Standard namespaces
  'ScalarValues', 'ISQ', 'SI', 'USCustomaryUnits', 'Quantities', 'Numerical',
]);

// Defensive: filter out anything that's a keyword.
for (const k of NEVER_TRANSLATE) {
  if (k in IDENT_MAP) delete (IDENT_MAP as Record<string, string>)[k];
}

// ─── Translation logic ──────────────────────────────────────────────────────

function translateContent(content: string): string {
  // Build a single regex matching all identifiers as whole words.
  // Sort keys longer-first so e.g. `BrakeSystem` matches before `Brake`.
  const keys = Object.keys(IDENT_MAP).sort((a, b) => b.length - a.length);
  if (keys.length === 0) return content;
  const escaped = keys.map(k => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  const re = new RegExp(`\\b(${escaped.join('|')})\\b`, 'g');
  return content.replace(re, (m) => IDENT_MAP[m] || m);
}

function translatePath(name: string, map: Record<string, string>): string {
  return map[name] || name;
}

function processDir(srcDir: string, dstDir: string, depth = 0): { dirs: number; files: number } {
  let dirs = 0;
  let files = 0;
  if (depth > 5) return { dirs, files };
  mkdirSync(dstDir, { recursive: true });

  for (const entry of readdirSync(srcDir, { withFileTypes: true })) {
    const srcPath = join(srcDir, entry.name);
    if (entry.isDirectory()) {
      if (EXCLUDE_DIRS.has(entry.name)) continue;
      const trName = translatePath(entry.name, FOLDER_MAP);
      const dstPath = join(dstDir, trName);
      const sub = processDir(srcPath, dstPath, depth + 1);
      dirs += sub.dirs + 1;
      files += sub.files;
    } else if (entry.isFile() && entry.name.endsWith('.sysml')) {
      const base = basename(entry.name, '.sysml');
      const trBase = translatePath(base, FILE_MAP);
      const dstPath = join(dstDir, `${trBase}.sysml`);
      const content = readFileSync(srcPath, 'utf-8');
      const translated = translateContent(content);
      writeFileSync(dstPath, translated, 'utf-8');
      files++;
    }
  }
  return { dirs, files };
}

// ─── Main ───────────────────────────────────────────────────────────────────

if (!existsSync(SRC)) {
  console.error(`Source directory not found: ${SRC}`);
  process.exit(1);
}

if (existsSync(DST)) {
  console.log(`Removing existing destination: ${DST}`);
  rmSync(DST, { recursive: true });
}

const { dirs, files } = processDir(SRC, DST);
console.log(`Translated ${dirs} directories, ${files} files → ${DST}`);
console.log(`Identifier map entries: ${Object.keys(IDENT_MAP).length}`);
